version: '3.3'

services:
  check-white-screen:
    build: .
    container_name: check-white-screen
    ports:
      - "33223:33223"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
